version: '3.3'
services:
  tool-exchange-front:
    image: markojerkic/tool-exchange-front
    container_name: tool-exchange-front
    ports:
      - 80:80
      - 443:80
    networks:
      - tool-exchange-network
  tool-exchange-service:
    image: markojerkic/tool-exchange-service
    container_name: tool-exchange-service
    build:
      context: .
    depends_on:
      - tool-db
    environment:
      - DB_HOST=tool-db
      - DB_PORT=5432
    ports:
      - 8080:8080
    networks:
      - tool-exchange-network
  tool-db:
      image: postgres
      container_name: tool-db
      environment:
        POSTGRES_USER: toolexchange
        POSTGRES_PASSWORD: toolexchange
        POSTGRES_DB: tooldb
        PGDATA: /var/lib/postgresql/data/dbdata
      ports:
        - 5000:5432
        - 5432:5432
      networks:
        - tool-exchange-network
      volumes:
        - dbdata:/var/lib/postgresql/data
      restart: always
volumes:
  dbdata:
networks:
  tool-exchange-network:
    name: tool-exchange-network
